apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-gcs-csi-static-example
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp-gcs-csi-static-example
  template:
    metadata:
      labels:
        app: gcp-gcs-csi-static-example
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      containers:
      - name: writer
        image: busybox
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 80Mi
        command:
          - "/bin/sh"
          - "-c"
          - touch /cs/${MY_POD_NAME} && while true; do echo $(date) >> /cs/${MY_POD_NAME}; sleep 1; done
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: gcp-gcs-csi-pvc
          mountPath: /cs
      serviceAccountName: testapp
      volumes:
      - name: gcp-gcs-csi-pvc
        persistentVolumeClaim:
          claimName: gcp-gcs-csi-static-pvc