apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcp-gcs-csi-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dummy-storage-class
  claimRef:
    namespace: default
    name: gcp-gcs-csi-static-pvc
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: lab-gke-se-hpc-1-bucket-1
