apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-gcs-csi-static-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: gcp-gcs-csi-pv
  storageClassName: dummy-storage-class
