createTime: '2024-07-23T16:15:02.222026Z'
etag: '"161dec76c2b0ca"'
name: projects/52991355109/secrets/hpc-1-certificates
replication:
  userManaged:
    replicas:
    - customerManagedEncryption:
        kmsKeyName: projects/lab-gke-se/locations/us-east4/keyRings/LAB-GKE-SE-gke-key-ring-uudp/cryptoKeys/LAB-GKE-SE-gke-key
      location: us-east4
