encryption:
  defaultKmsKeyName: projects/lab-gke-se/locations/us-central1/keyRings/hpc-1-us-central1-kza4/cryptoKeys/hpc-1-us-central1
defaultStorageClass: STANDARD
location: US-CENTRAL1
name: lab-gke-se-hpc-1-source
softDeletePolicy:
  retentionDurationSeconds: '604800'
iamConfiguration:
  publicAccessPrevention: enforced
  uniformBucketLevelAccess: 
    enabled: true
versioning: 
  enabled: true