default_kms_key: projects/lab-gke-se/locations/us-central1/keyRings/hpc-1-us-central1-kza4/cryptoKeys/hpc-1-us-central1
default_storage_class: STANDARD
location: US-CENTRAL1
location_type: region
name: lab-gke-se-hpc-1-source
public_access_prevention: enforced
soft_delete_policy:
  retentionDurationSeconds: '604800'
storage_url: gs://lab-gke-se-hpc-1-source/
uniform_bucket_level_access: true
versioning_enabled: true
