encryption:
  defaultKmsKeyName: projects/lab-gke-se/locations/us-east4/keyRings/hpc-1-8uhu/cryptoKeys/hpc-1
defaultStorageClass: STANDARD
location: US-EAST4
name: lab-gke-se-hpc-1-bucket-1
softDeletePolicy:
  retentionDurationSeconds: '604800'
iamConfiguration:
  publicAccessPrevention: enforced
  uniformBucketLevelAccess: 
    enabled: true
versioning: 
  enabled: true