apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: us-central1-docker.pkg.dev/lab-gke-se/hpc-1-images/hpc-1-worker-k8:v0.0.1
