apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudstorage-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: cloudstorage-class
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: lab-gke-se-hpc-1-bucket-3
    volumeAttributes:
      gcsfuseLoggingSeverity: warning