apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudstorage-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: cloudstorage-pv
  storageClassName: cloudstorage-class