apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pubsub-scaledobject
spec:
  pollingInterval: 10 
  cooldownPeriod:  10 
  maxReplicaCount: 5000
  minReplicaCount: 0
  scaleTargetRef:
    name: pass
  triggers:
    - type: gcp-pubsub
      authenticationRef:
        name: keda-workload-identity-auth
      metadata:
        subscriptionName: hpc-1-messages
