# Template for standard clusters test
addonsConfig:
  dnsCacheConfig:
    enabled: true
  gcePersistentDiskCsiDriverConfig:
    enabled: true
  gcpFilestoreCsiDriverConfig:
    enabled: true
  gcsFuseCsiDriverConfig:
    enabled: true
  kubernetesDashboard:
    disabled: true
  networkPolicyConfig:
    disabled: true
  statefulHaConfig:
    enabled: true
autopilot: {}
autoscaling:
  autoprovisioningNodePoolDefaults:
    bootDiskKmsKey: ${kms_key}
    diskSizeGb: 100
    diskType: pd-balanced
    imageType: COS_CONTAINERD
    management:
      autoRepair: true
      autoUpgrade: true
      upgradeOptions: {}
    oauthScopes:
    - https://www.googleapis.com/auth/userinfo.email
    - https://www.googleapis.com/auth/cloud-platform
    serviceAccount: ${service_account}
    upgradeSettings:
      maxSurge: 1
      strategy: SURGE
  autoscalingProfile: OPTIMIZE_UTILIZATION
  enableNodeAutoprovisioning: true
  resourceLimits:
  - maximum: '1000000000'
    resourceType: cpu
  - maximum: '1000000000'
    resourceType: memory
  - maximum: '1000000000'
    resourceType: nvidia-tesla-t4
  - maximum: '1000000000'
    resourceType: nvidia-tesla-a100
binaryAuthorization: {}
controlPlaneEndpointsConfig:
  dnsEndpointConfig:
    allowExternalTraffic: true
  enhancedIngress:
currentMasterVersion: 1.30.3-gke.1969001
currentNodeCount: 3
currentNodeVersion: 1.30.3-gke.1969001
databaseEncryption:
  currentState: CURRENT_STATE_ENCRYPTED
  keyName: ${kms_key}
  state: ENCRYPTED
defaultMaxPodsConstraint:
  maxPodsPerNode: '110'
enterpriseConfig:
  clusterTier: STANDARD
initialClusterVersion: 1.30.3-gke.1969001
initialNodeCount: 1
ipAllocationPolicy:
  clusterSecondaryRangeName: gke-pods
  podCidrOverprovisionConfig: {}
  servicesSecondaryRangeName: gke-services
  stackType: IPV4
  useIpAliases: true
legacyAbac: {}
location: us-east4
locations:
- us-east4-a
- us-east4-b
- us-east4-c
loggingConfig:
  componentConfig:
    enableComponents:
    - SYSTEM_COMPONENTS
    - WORKLOADS
loggingService: logging.googleapis.com/kubernetes
maintenancePolicy:
  window:
    dailyMaintenanceWindow:
      duration: PT4H0M0S
      startTime: 05:00
masterAuth:
  clientCertificateConfig: {}
masterAuthorizedNetworksConfig:
  cidrBlocks:
  - cidrBlock: 77.101.187.225/32
    displayName: Dave's Home
  enabled: true
  gcpPublicCidrsAccessEnabled: false
monitoringConfig:
  advancedDatapathObservabilityConfig:
    enableMetrics: true
  componentConfig:
    enableComponents:
    - SYSTEM_COMPONENTS
    - DAEMONSET
    - DEPLOYMENT
    - STATEFULSET
    - STORAGE
    - HPA
    - POD
    # - CADVISOR
    # - KUBELET
  managedPrometheusConfig:
    enabled: true
monitoringService: monitoring.googleapis.com/kubernetes
name: hpc-1-standard-2
network: hpc-1
networkConfig:
  datapathProvider: ADVANCED_DATAPATH
  defaultSnatStatus: {}
  dnsConfig:
    clusterDns: CLOUD_DNS
    clusterDnsDomain: cluster.local
    clusterDnsScope: CLUSTER_SCOPE
  enableIntraNodeVisibility: true
  gatewayApiConfig:
    channel: CHANNEL_STANDARD
  network: projects/lab-gke-se/global/networks/hpc-1
  serviceExternalIpsConfig: {}
  subnetwork: projects/lab-gke-se/regions/us-east4/subnetworks/hpc-1-cluster-2
nodeConfig:
  bootDiskKmsKey: ${kms_key}
  diskSizeGb: 100
  diskType: pd-balanced
  imageType: COS_CONTAINERD
  loggingConfig: {}
  machineType: e2-small
  metadata:
    disable-legacy-endpoints: 'true'
  oauthScopes:
  - https://www.googleapis.com/auth/userinfo.email
  - https://www.googleapis.com/auth/cloud-platform
  reservationAffinity:
    consumeReservationType: NO_RESERVATION
  serviceAccount: ${service_account}
  shieldedInstanceConfig:
    enableIntegrityMonitoring: true
    enableSecureBoot: true
  taints:
  - effect: NO_SCHEDULE
    key: cloud.google.com/gke-quick-remove
    value: 'true'
  windowsNodeConfig: {}
  workloadMetadataConfig:
    mode: GKE_METADATA
nodePoolDefaults:
  nodeConfigDefaults:
    loggingConfig:
      variantConfig:
        variant: DEFAULT
nodePools:
- autoscaling:
    enabled: true
    locationPolicy: BALANCED
    maxNodeCount: 1000
  config:
    bootDiskKmsKey: ${kms_key}
    diskSizeGb: 100
    diskType: pd-balanced
    imageType: COS_CONTAINERD
    loggingConfig: {}
    machineType: e2-small
    metadata:
      disable-legacy-endpoints: 'true'
    oauthScopes:
    - https://www.googleapis.com/auth/userinfo.email
    - https://www.googleapis.com/auth/cloud-platform
    reservationAffinity:
      consumeReservationType: NO_RESERVATION
    serviceAccount: ${service_account}
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    taints:
    - effect: NO_SCHEDULE
      key: cloud.google.com/gke-quick-remove
      value: 'true'
    windowsNodeConfig: {}
    workloadMetadataConfig:
      mode: GKE_METADATA
  etag: 9a22c39c-2b89-4011-bb2e-ea653aeb9b98
  initialNodeCount: 1
  locations:
  - us-east4-a
  - us-east4-b
  - us-east4-c
  management:
    autoRepair: true
    autoUpgrade: true
  maxPodsConstraint:
    maxPodsPerNode: '32'
  name: default-pool-new
  networkConfig:
    enablePrivateNodes: true
    podIpv4CidrBlock: 240.1.64.0/19
    podRange: gke-pods
  podIpv4CidrSize: 26
  upgradeSettings:
    maxSurge: 1
    strategy: SURGE
  version: 1.29.6-gke.1038001
- autoscaling:
    enabled: true
    locationPolicy: BALANCED
    maxNodeCount: 1000
  config:
    bootDiskKmsKey: ${kms_key}
    diskSizeGb: 100
    diskType: pd-balanced
    imageType: COS_CONTAINERD
    loggingConfig: {}
    machineType: e2-medium
    metadata:
      disable-legacy-endpoints: 'true'
    oauthScopes:
    - https://www.googleapis.com/auth/userinfo.email
    - https://www.googleapis.com/auth/cloud-platform
    reservationAffinity:
      consumeReservationType: NO_RESERVATION
    serviceAccount: ${service_account}
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    windowsNodeConfig: {}
    workloadMetadataConfig:
      mode: GKE_METADATA
  etag: d3946bf6-7f10-40c5-a011-7161a1a09177
  locations:
  - us-east4-a
  - us-east4-b
  - us-east4-c
  management:
    autoRepair: true
    autoUpgrade: true
  maxPodsConstraint:
    maxPodsPerNode: '32'
  name: pool-1
  networkConfig:
    enablePrivateNodes: true
    podIpv4CidrBlock: 240.1.64.0/19
    podRange: gke-pods
  podIpv4CidrSize: 26
  upgradeSettings:
    maxSurge: 1
    strategy: SURGE
  version: 1.29.6-gke.1038001
- autoscaling:
    enabled: true
    locationPolicy: BALANCED
    maxNodeCount: 1000
  config:
    bootDiskKmsKey: ${kms_key}
    diskSizeGb: 100
    diskType: pd-balanced
    imageType: COS_CONTAINERD
    loggingConfig: {}
    machineType: e2-standard-2
    metadata:
      disable-legacy-endpoints: 'true'
    oauthScopes:
    - https://www.googleapis.com/auth/userinfo.email
    - https://www.googleapis.com/auth/cloud-platform
    reservationAffinity:
      consumeReservationType: NO_RESERVATION
    serviceAccount: ${service_account}
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    windowsNodeConfig: {}
    workloadMetadataConfig:
      mode: GKE_METADATA
  locations:
  - us-east4-a
  - us-east4-b
  - us-east4-c
  management:
    autoRepair: true
    autoUpgrade: true
  maxPodsConstraint:
    maxPodsPerNode: '32'
  name: pool-2
  networkConfig:
    enablePrivateNodes: true
    podIpv4CidrBlock: 240.1.64.0/19
    podRange: gke-pods
  podIpv4CidrSize: 26
  status: RUNNING
  upgradeSettings:
    maxSurge: 1
    strategy: SURGE
  version: 1.29.6-gke.1038001
- autoscaling:
    enabled: true
    locationPolicy: BALANCED
    maxNodeCount: 1000
  config:
    bootDiskKmsKey: ${kms_key}
    diskSizeGb: 100
    diskType: pd-balanced
    imageType: COS_CONTAINERD
    loggingConfig: {}
    machineType: e2-standard-4
    metadata:
      disable-legacy-endpoints: 'true'
    oauthScopes:
    - https://www.googleapis.com/auth/userinfo.email
    - https://www.googleapis.com/auth/cloud-platform
    reservationAffinity:
      consumeReservationType: NO_RESERVATION
    serviceAccount: ${service_account}
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    windowsNodeConfig: {}
    workloadMetadataConfig:
      mode: GKE_METADATA
  locations:
  - us-east4-a
  - us-east4-b
  - us-east4-c
  management:
    autoRepair: true
    autoUpgrade: true
  maxPodsConstraint:
    maxPodsPerNode: '32'
  name: pool-3
  networkConfig:
    enablePrivateNodes: true
    podIpv4CidrBlock: 240.1.64.0/19
    podRange: gke-pods
  podIpv4CidrSize: 26
  status: RUNNING
  upgradeSettings:
    maxSurge: 1
    strategy: SURGE
  version: 1.29.6-gke.1038001
- autoscaling:
    enabled: true
    locationPolicy: BALANCED
    maxNodeCount: 1000
  config:
    bootDiskKmsKey: ${kms_key}
    diskSizeGb: 100
    diskType: pd-balanced
    imageType: COS_CONTAINERD
    loggingConfig: {}
    machineType: e2-standard-8
    metadata:
      disable-legacy-endpoints: 'true'
    oauthScopes:
    - https://www.googleapis.com/auth/userinfo.email
    - https://www.googleapis.com/auth/cloud-platform
    reservationAffinity:
      consumeReservationType: NO_RESERVATION
    serviceAccount: ${service_account}
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    windowsNodeConfig: {}
    workloadMetadataConfig:
      mode: GKE_METADATA
  locations:
  - us-east4-a
  - us-east4-b
  - us-east4-c
  management:
    autoRepair: true
    autoUpgrade: true
  maxPodsConstraint:
    maxPodsPerNode: '32'
  name: pool-4
  networkConfig:
    enablePrivateNodes: true
    podIpv4CidrBlock: 240.1.64.0/19
    podRange: gke-pods
  podIpv4CidrSize: 26
  upgradeSettings:
    maxSurge: 1
    strategy: SURGE
  version: 1.29.6-gke.1038001
- autoscaling:
    enabled: true
    locationPolicy: BALANCED
    maxNodeCount: 1000
  config:
    bootDiskKmsKey: ${kms_key}
    diskSizeGb: 100
    diskType: pd-balanced
    imageType: COS_CONTAINERD
    loggingConfig: {}
    machineType: e2-standard-16
    metadata:
      disable-legacy-endpoints: 'true'
    oauthScopes:
    - https://www.googleapis.com/auth/userinfo.email
    - https://www.googleapis.com/auth/cloud-platform
    reservationAffinity:
      consumeReservationType: NO_RESERVATION
    serviceAccount: ${service_account}
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    windowsNodeConfig: {}
    workloadMetadataConfig:
      mode: GKE_METADATA
  locations:
  - us-east4-a
  - us-east4-b
  - us-east4-c
  management:
    autoRepair: true
    autoUpgrade: true
  maxPodsConstraint:
    maxPodsPerNode: '32'
  name: pool-5
  networkConfig:
    enablePrivateNodes: true
    podIpv4CidrBlock: 240.1.64.0/19
    podRange: gke-pods
  podIpv4CidrSize: 26
  upgradeSettings:
    maxSurge: 1
    strategy: SURGE
  version: 1.29.6-gke.1038001
- autoscaling:
    enabled: true
    locationPolicy: BALANCED
    maxNodeCount: 1000
  config:
    bootDiskKmsKey: ${kms_key}
    diskSizeGb: 100
    diskType: pd-balanced
    imageType: COS_CONTAINERD
    loggingConfig: {}
    machineType: e2-standard-32
    metadata:
      disable-legacy-endpoints: 'true'
    oauthScopes:
    - https://www.googleapis.com/auth/userinfo.email
    - https://www.googleapis.com/auth/cloud-platform
    reservationAffinity:
      consumeReservationType: NO_RESERVATION
    serviceAccount: ${service_account}
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    windowsNodeConfig: {}
    workloadMetadataConfig:
      mode: GKE_METADATA
  locations:
  - us-east4-a
  - us-east4-b
  - us-east4-c
  management:
    autoRepair: true
    autoUpgrade: true
  maxPodsConstraint:
    maxPodsPerNode: '32'
  name: pool-6
  networkConfig:
    enablePrivateNodes: true
    podIpv4CidrBlock: 240.1.64.0/19
    podRange: gke-pods
  podIpv4CidrSize: 26
  status: RUNNING
  upgradeSettings:
    maxSurge: 1
    strategy: SURGE
  version: 1.29.6-gke.1038001
notificationConfig:
  pubsub: {}
privateClusterConfig:
  enablePrivateNodes: true
  masterIpv4CidrBlock: 10.200.1.0/28
  privateEndpoint: 10.200.1.2
  publicEndpoint: 35.245.102.58
rbacBindingConfig:
  enableInsecureBindingSystemAuthenticated: true
  enableInsecureBindingSystemUnauthenticated: true
releaseChannel:
  channel: REGULAR
securityPostureConfig:
  mode: DISABLED
  vulnerabilityMode: VULNERABILITY_DISABLED
servicesIpv4Cidr: 240.2.36.0/22
shieldedNodes:
  enabled: true
status: RUNNING
subnetwork: hpc-1-cluster-2
verticalPodAutoscaling:
  enabled: true
workloadIdentityConfig:
  workloadPool: lab-gke-se.svc.id.goog
zone: us-east4
