description: HPC 1 Worker Function Service Account
displayName: HPC 1 Worker Function Service Account
email: hpc-1-worker@lab-gke-se.iam.gserviceaccount.com
name: projects/lab-gke-se/serviceAccounts/hpc-1-worker@lab-gke-se.iam.gserviceaccount.com
projectId: lab-gke-se
