description: HPC 1 Cluster Node Service Account
displayName: HPC 1 Cluster Node Service Account
email: hpc-1-nodes@lab-gke-se.iam.gserviceaccount.com
name: projects/lab-gke-se/serviceAccounts/hpc-1-nodes@lab-gke-se.iam.gserviceaccount.com
projectId: lab-gke-se
