done: true
metadata:
  '@type': type.googleapis.com/google.cloud.parallelstore.v1alpha.OperationMetadata
  apiVersion: v1alpha
  createTime: '2024-09-30T13:08:49.145696878Z'
  endTime: '2024-09-30T13:16:10.349174232Z'
  requestedCancellation: false
  target: projects/lab-gke-se/locations/us-central1-a/instances/hpc-1-storage
  verb: create
name: projects/lab-gke-se/locations/us-central1-a/operations/operation-1727701728005-62355e7c68d74-57d6ed56-a3a6b109
response:
  '@type': type.googleapis.com/google.cloud.parallelstore.v1alpha.Instance
  accessPoints:
  - 10.19.136.67
  - 10.19.136.69
  - 10.19.136.68
  capacityGib: '16000'
  createTime: '2024-09-30T13:08:49.142301358Z'
  effectiveReservedIpRange: hpc-1-parallelstore-1
  name: projects/lab-gke-se/locations/us-central1-a/instances/hpc-1-storage
  network: projects/lab-gke-se/global/networks/hpc-1
  state: ACTIVE
  updateTime: '2024-09-30T13:08:49.142301358Z'
