accessPoints:
- 10.19.136.3
- 10.19.136.4
- 10.19.136.2
capacityGib: '12000'
createTime: '2024-10-09T09:23:51.833564332Z'
directoryStripeLevel: DIRECTORY_STRIPE_LEVEL_BALANCED
effectiveReservedIpRange: hpc-1-parallelstore-1
fileStripeLevel: FILE_STRIPE_LEVEL_BALANCED
name: projects/lab-gke-se/locations/us-east4-a/instances/hpc-1-storage-1
network: projects/lab-gke-se/global/networks/hpc-1
state: ACTIVE
updateTime: '2024-10-09T09:31:19.821413569Z'
