name : Message Producer
description: Produces message to test consumers
runtime: python311
availableMemoryMb: 256
serviceAccountEmail: ${producer_service_account}
sourceArchiveUrl: hpc-1-source
sourceUploadUrl: hpc-1-source/producer.zip
kmsKeyName: ${kms_key_usc1}
eventTrigger: ${producer_topic_name}
entryPoint: event_handler
dockerRepository: ${artifact_registry}

vpcConnector: TBD
vpcConnectorEgressSettings: TBD
ingressSettings: TBD

environmentVariables:
- STORAGE_BUCKET: name
- ALERT_TOPIC: test
