- autoscaling:
    enabled: true
    locationPolicy: BALANCED
    maxNodeCount: 1000
  config:
    bootDiskKmsKey: ${kms_key}
    diskSizeGb: 100
    diskType: pd-balanced
    imageType: COS_CONTAINERD
    machineType: e2-medium
    metadata:
      disable-legacy-endpoints: 'true'
    oauthScopes:
    - https://www.googleapis.com/auth/userinfo.email
    - https://www.googleapis.com/auth/cloud-platform
    reservationAffinity:
      consumeReservationType: NO_RESERVATION
    serviceAccount: ${service_account}
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    windowsNodeConfig: {}
    # workloadMetadataConfig:
    #   mode: GKE_METADATA
  etag: d3946bf6-7f10-40c5-a011-7161a1a09177
  instanceGroupUrls:
  - https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/instanceGroupManagers/gk3-tenant-gke-private-cluster-pool-1-482784c4-grp
  - https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-b/instanceGroupManagers/gk3-tenant-gke-private-cluster-pool-1-9ebeb029-grp
  - https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-c/instanceGroupManagers/gk3-tenant-gke-private-cluster-pool-1-032902a6-grp
  locations:
  - us-east4-a
  - us-east4-b
  - us-east4-c
  management:
    autoRepair: true
    autoUpgrade: true
  maxPodsConstraint:
    maxPodsPerNode: '32'
  name: pool-1
  networkConfig:
    enablePrivateNodes: true
    podIpv4CidrBlock: 240.1.64.0/19
    podRange: gke-pods
  podIpv4CidrSize: 26
  selfLink: https://container.googleapis.com/v1/projects/lab-gke-se/locations/us-east4/clusters/tenant-gke-private-cluster/nodePools/pool-1
  status: RUNNING
  upgradeSettings:
    maxSurge: 1
    strategy: SURGE
  version: 1.29.6-gke.1038001
