allowed:
- IPProtocol: tcp
direction: INGRESS
disabled: false
logConfig:
  enable: false
name: hpc-1-allow-parallelstore-1
network: projects/lab-gke-se/global/networks/hpc-1
priority: 990
sourceRanges:
- 10.19.136.0/24
